name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'      # required: e.g. 'temurin', 'adopt', 'zulu', etc.
            java-version: '11'           # required: the Java version you need
            cache: 'maven'               # optional, if you want to cache your Maven dependencies
      - name: Run JUnit tests
        run: mvn test
      - name: Log workflow execution parameters
        run: |
            echo "execution_parameter:: $(echo '${{ toJson(github.event.inputs) }}' | jq -c .)"

  octane_integration:
    needs: test
    runs-on: ubuntu-latest
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v25.2.1
        with:
          octaneUrl:          'https://almoctane-ams.saas.microfocus.com'
          octaneSharedSpace:  '466026'
          octaneWorkspace:    '1002'
          octaneClientId:     ${{ secrets.OCTANE_CLIENT_ID }}
          octaneClientSecret: ${{ secrets.OCTANE_CLIENT_SECRET }}
          githubToken:        ${{ secrets.GITHUB_TOKEN }}
          serverBaseUrl:    https://github.com/davbaster/junit-calculator-gha
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: '**/target/surefire-reports/*.xml'
          testingFramework: 'junit'
